[pytest]
addopts = -s -ra -v 
#--strict-markers
testpaths=
    tests
    #app
pythonpath=
    #.
    #app
    #app/lib
    #tests
markers = 
    webtest: mark a test as a webtest.
     slow: mark test as slow. 
     freeze_time: foo
python_files =
    *.py
